#!/usr/bin/with-contenv bash

echo "Checking for valid arch options"
case $ARCH_VAR in
  x86_64)
    echo "Proceeding with x86-64 arch"
    ;;
  aarch64)
    echo "Proceeding with aarch64 arch"
    ;;
  arm)
    echo "Proceeding with arm arch"
    ;;
  *)
    echo "Unrecognized or invalid arch selection, canceling install"
    exit 1
    ;;
esac

# Grab latest versions of the app
wget -O /bin/airupnp-$ARCH_VAR https://cdn.jsdelivr.net/gh/philippe44/AirConnect@master/bin/airupnp-linux-$ARCH_VAR && chmod +x /bin/airupnp-$ARCH_VAR
wget -O /bin/aircast-$ARCH_VAR https://cdn.jsdelivr.net/gh/philippe44/AirConnect@master/bin/aircast-linux-$ARCH_VAR && chmod +x /bin/aircast-$ARCH_VAR

# Insert runtime commands if users has entered them as environment variables
[ -z "$AIRUPNP_VAR" ] && sed -i 's;command=/bin/airupnp-x86_64 -l 1000:2000;command=/bin/airupnp-'"$ARCH_VAR"' -l 1000:2000;' /etc/supervisord.conf || sed -i 's;command=/bin/airupnp-x86_64 -l 1000:2000;command=/bin/airupnp-'"$ARCH_VAR $AIRUPNP_VAR"';' /etc/supervisord.conf
[ -z "$AIRCAST_VAR" ] && sed -i 's;command=/bin/aircast-x86_64;command=/bin/aircast-'"$ARCH_VAR"';' /etc/supervisord.conf || sed -i 's;command=/bin/aircast-x86_64;command=/bin/aircast-'"$ARCH_VAR $AIRCAST_VAR"';' /etc/supervisord.conf

# Adjusting process names in supervisord
[ "$ARCH_VAR" != "x86_64" ] && sed -i 's;process_name = airupnp-x86_64;process_name = airupnp-'"$ARCH_VAR"';' /etc/supervisord.conf
[ "$ARCH_VAR" != "x86_64" ] && sed -i 's;process_name = aircast-x86_64;process_name = aircast-'"$ARCH_VAR"';' /etc/supervisord.conf
